<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Regression" duration-ms="125" started-at="2015-06-05T16:33:48Z" finished-at="2015-06-05T16:33:48Z">
    <groups>
    </groups>
    <test name="RegressionCore" duration-ms="125" started-at="2015-06-05T16:33:48Z" finished-at="2015-06-05T16:33:48Z">
      <class name="coretest.CoreTestCase">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:coretest.CoreTestCase@13c438e]" name="beforeSuite" is-config="true" duration-ms="126" started-at="2015-06-05T17:33:48Z" finished-at="2015-06-05T17:33:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="FAIL" signature="loggingTestFail()[pri:0, instance:coretest.CoreTestCase@13c438e]" name="loggingTestFail" duration-ms="45" started-at="2015-06-05T17:33:48Z" finished-at="2015-06-05T17:33:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at coretest.CoreTestCase.loggingTestFail(CoreTestCase.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loggingTestFail -->
        <test-method status="PASS" signature="loggingTestPass()[pri:0, instance:coretest.CoreTestCase@13c438e]" name="loggingTestPass" duration-ms="5" started-at="2015-06-05T17:33:48Z" finished-at="2015-06-05T17:33:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loggingTestPass -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:coretest.CoreTestCase@13c438e]" name="afterSuite" is-config="true" duration-ms="4" started-at="2015-06-05T17:33:49Z" finished-at="2015-06-05T17:33:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- coretest.CoreTestCase -->
    </test> <!-- RegressionCore -->
  </suite> <!-- Regression -->
</testng-results>
